---
- name: Ensure service is started/stopped
  service:
    name: '{{ pacemaker_service }}'
    state: '{{ pacemaker_service_state }}'
    enabled: '{{ pacemaker_service_enabled }}'
  tags:
   - pacemaker
   - service

- name: Ensure pcsd service is started/stopped
  service:
    name: pcsd
    state: stopped
    enabled: no
  tags:
   - corosync
   - service
